In [1]:
from pathlib import Path

In [2]:
base=Path.cwd().parent
print(base)

D:\P_PC_CHATBOT\SQL_AGENT

In [3]:
import yaml
file=f"{base}/Data/lms.yml"
with open(file,'r',encoding="utf-8") as f:
    d=yaml.safe_load(f)

In [4]:
d

{'Table_Name1': 'lms.tm',
 'Table_Description1': 'Table for storing training module information for SOP based trainings',
 'Table_Name2': 'lms.tm_attachment',
 'Table_Description2': 'Table for storing attachments like docs pdfs etc.. related to SOP training modules',
 'Table_Name3': 'lms.training',
 'Table_Description3': 'Table for storing training modules information for Manage Trainings Quick Trainings party based trainings all trainings except SOP based trainings',
 'Table_Name4': 'lms.training_attachment',
 'Table_Description4': 'Table for storing attachments like docs pdfs etc.. related to Manage Trainings Quick Trainings party based trainings all trainings except SOP based trainings',
 'Table_Name5': 'lms.user_training',
 'Table_Description5': 'Table for storing user training information for all trainings',
 'Table_Name6': 'masters.party',
 'Table_Description6': 'Table for storing all user information in the organization',
 'Table_Name7': 'masters.party_role',
 'Table_Description7': 'Table for storing all user roles information in the organization',
 'Table_Name8': 'masters.product_store',
 'Table_Description8': 'Table for storing all department names and details in the organization'}

In [5]:
semantics=[k for v,k in d.items() if 'Table_Description' in v]
semantics

['Table for storing training module information for SOP based trainings',
 'Table for storing attachments like docs pdfs etc.. related to SOP training modules',
 'Table for storing training modules information for Manage Trainings Quick Trainings party based trainings all trainings except SOP based trainings',
 'Table for storing attachments like docs pdfs etc.. related to Manage Trainings Quick Trainings party based trainings all trainings except SOP based trainings',
 'Table for storing user training information for all trainings',
 'Table for storing all user information in the organization',
 'Table for storing all user roles information in the organization',
 'Table for storing all department names and details in the organization']

In [6]:
len(d)

16

In [7]:
import pandas as pd

rows = []

for i in range(1, len(d)//2 + 1):
    table_name = d.get(f"Table_Name{i}")
    table_description = d.get(f"Table_Description{i}")

    if table_name or table_description:
        rows.append({
            "Table_Name": table_name,
            "Table_Description": table_description
        })

df = pd.DataFrame(rows)

df.to_csv("semantic_kb.csv", index=False, encoding="utf-8")

print(df)

                Table_Name                                  Table_Description
0                   lms.tm  Table for storing training module information ...
1        lms.tm_attachment  Table for storing attachments like docs pdfs e...
2             lms.training  Table for storing training modules information...
3  lms.training_attachment  Table for storing attachments like docs pdfs e...
4        lms.user_training  Table for storing user training information fo...
5            masters.party  Table for storing all user information in the ...
6       masters.party_role  Table for storing all user roles information i...
7    masters.product_store  Table for storing all department names and det...

In [8]:
rows

[{'Table_Name': 'lms.tm',
  'Table_Description': 'Table for storing training module information for SOP based trainings'},
 {'Table_Name': 'lms.tm_attachment',
  'Table_Description': 'Table for storing attachments like docs pdfs etc.. related to SOP training modules'},
 {'Table_Name': 'lms.training',
  'Table_Description': 'Table for storing training modules information for Manage Trainings Quick Trainings party based trainings all trainings except SOP based trainings'},
 {'Table_Name': 'lms.training_attachment',
  'Table_Description': 'Table for storing attachments like docs pdfs etc.. related to Manage Trainings Quick Trainings party based trainings all trainings except SOP based trainings'},
 {'Table_Name': 'lms.user_training',
  'Table_Description': 'Table for storing user training information for all trainings'},
 {'Table_Name': 'masters.party',
  'Table_Description': 'Table for storing all user information in the organization'},
 {'Table_Name': 'masters.party_role',
  'Table_Description': 'Table for storing all user roles information in the organization'},
 {'Table_Name': 'masters.product_store',
  'Table_Description': 'Table for storing all department names and details in the organization'}]

In [9]:
df=pd.read_csv("semantic_kb.csv",encoding="utf-8")
df.to_dict()

{'Table_Name': {0: 'lms.tm',
  1: 'lms.tm_attachment',
  2: 'lms.training',
  3: 'lms.training_attachment',
  4: 'lms.user_training',
  5: 'masters.party',
  6: 'masters.party_role',
  7: 'masters.product_store'},
 'Table_Description': {0: 'Table for storing training module information for SOP based trainings',
  1: 'Table for storing attachments like docs pdfs etc.. related to SOP training modules',
  2: 'Table for storing training modules information for Manage Trainings Quick Trainings party based trainings all trainings except SOP based trainings',
  3: 'Table for storing attachments like docs pdfs etc.. related to Manage Trainings Quick Trainings party based trainings all trainings except SOP based trainings',
  4: 'Table for storing user training information for all trainings',
  5: 'Table for storing all user information in the organization',
  6: 'Table for storing all user roles information in the organization',
  7: 'Table for storing all department names and details in the organization'}}

In [10]:
df.shape

(8, 2)

In [11]:
import requests

OLLAMA_URL = "http://192.168.21.35:11434/api/embeddings"
EMBED_MODEL = "nomic-embed-text"

In [12]:
emb=[]
for i in range(len(df)):
    text = df.iloc[i]['Table_Description']

    response = requests.post(
        OLLAMA_URL,
        json={
            "model": EMBED_MODEL,
            "prompt": text
        }
    )

    response.raise_for_status()

    emb.append(response.json()["embedding"])
    embedding=emb[-1]
    print("Dimensions:", len(embedding))
    print(embedding[:10])

Dimensions: 768
[-1.0574955940246582, 1.2831698656082153, -3.701777458190918, -1.37651526927948, 0.6760948300361633, -0.554801344871521, 0.8727127909660339, 0.39610669016838074, -0.5791922807693481, -0.404957115650177]

Dimensions: 768
[-0.3467835783958435, 1.1310498714447021, -3.521287202835083, -1.717758059501648, 0.39166009426116943, -0.6719918847084045, 0.07186392694711685, 0.7608057260513306, -0.5556719303131104, -0.25618815422058105]

Dimensions: 768
[-1.387843370437622, 1.1915342807769775, -3.626025676727295, -0.7977135181427002, 0.5775039196014404, -0.45528778433799744, 0.7267078757286072, -0.03308631479740143, -0.5943143367767334, -1.0737937688827515]

Dimensions: 768
[-0.6275388598442078, 1.0483890771865845, -3.5290164947509766, -0.9860851764678955, 0.2509511411190033, -0.8141703009605408, 0.43232208490371704, 0.24298931658267975, -0.47712093591690063, -0.7736989259719849]

Dimensions: 768
[-1.0158430337905884, 1.3814443349838257, -3.8501193523406982, -0.7015458345413208, 0.7755382061004639, -0.8298851847648621, 1.18863046169281, 0.06373743712902069, -0.6269083619117737, -0.7908869981765747]

Dimensions: 768
[0.01959608867764473, 1.5767180919647217, -3.504926919937134, -0.7856428623199463, 0.5185017585754395, -1.0043202638626099, -0.08684395253658295, 0.10155361145734787, -0.6355414390563965, -0.12608183920383453]

Dimensions: 768
[-0.5321263670921326, 1.518287181854248, -3.6720662117004395, -0.8960283994674683, 0.960849404335022, -1.2517430782318115, 0.39863094687461853, -0.23785725235939026, -0.19173647463321686, 0.17732512950897217]

Dimensions: 768
[0.40705761313438416, 1.2951828241348267, -3.675231456756592, -1.949273943901062, -0.4067974090576172, -1.6574053764343262, -0.5678442716598511, -0.512701153755188, -0.10853985697031021, -0.17402049899101257]

In [13]:
df["embeddings"]=emb

In [14]:
df

,Table_Name,Table_Description,embeddings
0,lms.tm,Table for storing training module information ...,"[-1.0574955940246582, 1.2831698656082153, -3.7..."
1,lms.tm_attachment,Table for storing attachments like docs pdfs e...,"[-0.3467835783958435, 1.1310498714447021, -3.5..."
2,lms.training,Table for storing training modules information...,"[-1.387843370437622, 1.1915342807769775, -3.62..."
3,lms.training_attachment,Table for storing attachments like docs pdfs e...,"[-0.6275388598442078, 1.0483890771865845, -3.5..."
4,lms.user_training,Table for storing user training information fo...,"[-1.0158430337905884, 1.3814443349838257, -3.8..."
5,masters.party,Table for storing all user information in the ...,"[0.01959608867764473, 1.5767180919647217, -3.5..."
6,masters.party_role,Table for storing all user roles information i...,"[-0.5321263670921326, 1.518287181854248, -3.67..."
7,masters.product_store,Table for storing all department names and det...,"[0.40705761313438416, 1.2951828241348267, -3.6..."

In [15]:
import requests
import numpy as np
import pandas as pd

OLLAMA_URL = "http://192.168.21.35:11434/api/embeddings"
EMBED_MODEL = "nomic-embed-text"


def get_embedding(text):
    response = requests.post(
        OLLAMA_URL,
        json={
            "model": EMBED_MODEL,
            "prompt": text
        },
        timeout=120
    )

    response.raise_for_status()

    return response.json()["embedding"]


def cosine_similarity(a, b):
    a = np.array(a, dtype=np.float32)
    b = np.array(b, dtype=np.float32)

    return np.dot(a, b) / (
        np.linalg.norm(a) * np.linalg.norm(b)
    )


def search_tables(question, top_k=10):

    # --------------------------------------------------
    # 1. Embed the user's question
    # --------------------------------------------------

    query_embedding = get_embedding(question)

    results = []

    # --------------------------------------------------
    # 2. Compare against every business meaning
    # --------------------------------------------------

    for _, row in df.iterrows():

        table_embedding = row["embeddings"]

        similarity = cosine_similarity(
            query_embedding,
            table_embedding
        )

        results.append({
                **row.to_dict(),
                "similarity": similarity
            })

    # --------------------------------------------------
    # 3. Rank highest similarity first
    # --------------------------------------------------

    results_df = pd.DataFrame(results)

    results_df = results_df.sort_values(
        "similarity",
        ascending=False
    ).reset_index(drop=True)

    return results_df.head(top_k)

In [16]:
question = "List all Trainings SOPs and other all  "

results = search_tables(question, top_k=5)

display(results)

,Table_Name,Table_Description,embeddings,similarity
0,lms.training,Table for storing training modules information...,"[-1.387843370437622, 1.1915342807769775, -3.62...",0.743606
1,lms.tm,Table for storing training module information ...,"[-1.0574955940246582, 1.2831698656082153, -3.7...",0.741871
2,lms.training_attachment,Table for storing attachments like docs pdfs e...,"[-0.6275388598442078, 1.0483890771865845, -3.5...",0.698679
3,lms.user_training,Table for storing user training information fo...,"[-1.0158430337905884, 1.3814443349838257, -3.8...",0.667549
4,lms.tm_attachment,Table for storing attachments like docs pdfs e...,"[-0.3467835783958435, 1.1310498714447021, -3.5...",0.663732

In [17]:
results.columns

Index(['Table_Name', 'Table_Description', 'embeddings', 'similarity'], dtype='str')

In [18]:
SEMANTIC_KB_PATH = base / "Data"/"semantic_kb.json"

print("Base:", base)
print("KB:", SEMANTIC_KB_PATH)
print("Exists:", SEMANTIC_KB_PATH.exists())

Base: D:\P_PC_CHATBOT\SQL_AGENT
KB: D:\P_PC_CHATBOT\SQL_AGENT\Data\semantic_kb.json
Exists: True

In [19]:
import json
with open(SEMANTIC_KB_PATH, "r", encoding="utf-8") as f:
    semantic_kb = json.load(f)

print("Loaded successfully")
print("Python type:", type(semantic_kb))

Loaded successfully
Python type: <class 'list'>

In [20]:
for table in semantic_kb:
    print(table.keys())

dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])
dict_keys(['database_name', 'schema_name', 'table_name', 'qualified_name', 'physical_qualified_name', 'business_name', 'business_meaning', 'business_purpose', 'row_grain', 'table_role', 'business_terms', 'aliases', 'likely_user_phrases', 'related_business_concepts', 'evidence', 'confidence', 'primary_keys', 'foreign_keys', 'incoming_foreign_keys', 'columns', 'table_relationship_role', 'useful_join_paths', 'common_filters', 'common_group_bys', 'common_aggregations', 'common_ranking_questions', 'date_time_columns', 'data_quality_notes'])

In [21]:
semantic_kb = [
    {
        "qualified_name": table.get("qualified_name"),
        "primary_keys": table.get("primary_keys", []),
        "foreign_keys": table.get("foreign_keys", []),
        "incoming_foreign_keys": table.get("incoming_foreign_keys", []),
        "table_relationship_role": table.get("table_relationship_role", []),
        "useful_join_paths": table.get("useful_join_paths", [])
    }
    for table in semantic_kb
]

In [22]:
for table in semantic_kb:
    print(table.get("qualified_name"),"-",table)

masters.request_type - {'qualified_name': 'masters.request_type', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference table with no direct relationships', 'useful_join_paths': []}
masters.party - {'qualified_name': 'masters.party', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'department_id', 'references_table': 'public.product_store', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'gender_id', 'references_table': 'public.gender', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'party_type_id', 'references_table': 'public.party_type', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'preferred_language_id', 'references_table': 'public.language', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'qr_code_id', 'references_table': 'public.qr_code', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'status_id', 'references_table': 'public.status', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Central entity table with relationships to other entity tables (gender, department, language, etc.)', 'useful_join_paths': ['Join with public.gender on gender_id to get gender details', 'Join with public.department on department_id to get department details', 'Join with public.party_type on party_type_id to get party type details', 'Join with public.language on preferred_language_id to get language details', 'Join with public.status on status_id to get status details', 'Join with public.qr_code on qr_code_id to get QR code details']}
masters.security_group_permission - {'qualified_name': 'masters.security_group_permission', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'group_id', 'references_table': 'public.security_group', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'permission_id', 'references_table': 'public.permission', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'status_id', 'references_table': 'public.status', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Central table for linking security groups to permissions through status and validity periods.', 'useful_join_paths': ['Join with security_group to get group details', 'Join with permission to get permission details', 'Join with status to get the current status of the permission assignment']}
masters.product_store_user_group - {'qualified_name': 'masters.product_store_user_group', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'party_id', 'references_table': 'public.party', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'product_store_id', 'references_table': 'public.product_store', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'user_group_id', 'references_table': 'public.user_group', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Associates user groups, product stores, and parties', 'useful_join_paths': ['Join with user_group to get user group details', 'Join with product_store to get product store details', 'Join with party to get party details']}
masters.sys_persistent_audit_event - {'qualified_name': 'masters.sys_persistent_audit_event', 'primary_keys': [{'column': 'event_id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Source of audit data', 'useful_join_paths': []}
masters.job_code - {'qualified_name': 'masters.job_code', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'dept_id', 'references_table': 'public.product_store', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference table for job roles, linked to departments', 'useful_join_paths': ['Join with product_store on dept_id to get department details', 'Join with user tables on approved_by_user, returned_by_user, or created_by_user to get user context']}
masters.status - {'qualified_name': 'masters.status', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'category_id', 'references_table': 'public.status_category', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference table for status definitions', 'useful_join_paths': ['Join with status_category to get the category of a status', 'Join with entities or other tables that reference status via foreign key']}
masters.leave - {'qualified_name': 'masters.leave', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'party_id', 'references_table': 'public.party', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'type_id', 'references_table': 'public.leave_type', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Central entity for leave management, linked to employees and leave types', 'useful_join_paths': ['Join with public.party to get employee details', 'Join with public.leave_type to get leave type descriptions']}
masters.party_type - {'qualified_name': 'masters.party_type', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference table for categorization', 'useful_join_paths': ['party_type JOIN party ON party.party_type_id = party_type.id']}
masters.contact_mech_type - {'qualified_name': 'masters.contact_mech_type', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference table for contact mechanism types', 'useful_join_paths': []}
masters.sys_persistent_audit_evt_data - {'qualified_name': 'masters.sys_persistent_audit_evt_data', 'primary_keys': [{'column': 'event_id', 'business_meaning': 'Primary key column that identifies a row in this table.'}, {'column': 'name', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'event_id', 'references_table': 'public.sys_persistent_audit_event', 'references_column': 'event_id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Child Table (Audit Event Data)', 'useful_join_paths': ["Join with 'sys_persistent_audit_event' on 'event_id' to get event metadata", "Join with other tables if 'event_id' is used as a foreign key elsewhere"]}
masters.role_type - {'qualified_name': 'masters.role_type', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference', 'useful_join_paths': []}
masters.permission - {'qualified_name': 'masters.permission', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'mod_id', 'references_table': 'public.mod', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Authorization Definition Table', 'useful_join_paths': ["Join with 'mod' table via 'mod_id' to understand which module the permission belongs to.", "Join with 'user' or 'role' tables (if available) to determine which users or roles have this permission."]}
masters.security_group - {'qualified_name': 'masters.security_group', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'mod_id', 'references_table': 'public.mod', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'status_id', 'references_table': 'public.status', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Central security entity with relationships to system modules and status definitions.', 'useful_join_paths': ["Join with 'public.mod' to understand which module this security group belongs to.", "Join with 'public.status' to determine the current status of the security group."]}
masters.status_category - {'qualified_name': 'masters.status_category', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference table with no direct relationships', 'useful_join_paths': []}
masters.request_history - {'qualified_name': 'masters.request_history', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'from_status_id', 'references_table': 'public.status', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'request_id', 'references_table': 'public.request', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'to_status_id', 'references_table': 'public.status', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Event Log for Request Lifecycle', 'useful_join_paths': ["Join with 'public.request' to get request details", "Join with 'public.status' to get status names", "Join with 'public.user' to get user details for 'created_by' and 'last_modified_by'"]}
masters.product_store_type - {'qualified_name': 'masters.product_store_type', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference table used to classify store structures or organizational units for products.', 'useful_join_paths': ['Join with product tables to associate products with store types', 'Join with store tables to classify store structures']}
masters.request - {'qualified_name': 'masters.request', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'approved_by_id', 'references_table': 'public.party', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'request_type_id', 'references_table': 'public.request_type', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'reviewed_by_id', 'references_table': 'public.party', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'status_id', 'references_table': 'public.status', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Central entity with many-to-one relationships to party, request_type, and status', 'useful_join_paths': ['Join with party to get approver/reviewer details', 'Join with request_type to get request category', 'Join with status to get current status description']}
masters.system_parameters - {'qualified_name': 'masters.system_parameters', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'product_id', 'references_table': 'public.product', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'product_store_id', 'references_table': 'public.product_store', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference Table for Configuration Parameters', 'useful_join_paths': ['Join with public.product on product_id to get product-specific context', 'Join with public.product_store on product_store_id to get store-specific context']}
masters.party_role - {'qualified_name': 'masters.party_role', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'party_id', 'references_table': 'public.party', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'role_type_id', 'references_table': 'public.role_type', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference table for role assignments', 'useful_join_paths': ["Join with 'party' to get party details", "Join with 'role_type' to get role type definitions"]}
masters.user_security_group - {'qualified_name': 'masters.user_security_group', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'party_id', 'references_table': 'public.party', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'security_group_id', 'references_table': 'public.security_group', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'status_id', 'references_table': 'public.status', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'user_group_id', 'references_table': 'public.user_group', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Central hub for user-to-security-group and user-to-user-group relationships', 'useful_join_paths': ['Join with public.party to get user details', 'Join with public.security_group to get security group details', 'Join with public.user_group to get user group details', 'Join with public.status to get membership status details']}
masters.mod - {'qualified_name': 'masters.mod', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference table with no direct relationships to other tables.', 'useful_join_paths': []}
masters.product_store - {'qualified_name': 'masters.product_store', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'parent_id', 'references_table': 'public.product_store', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'type_id', 'references_table': 'public.product_store_type', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Hierarchical and typed categorization of organizational units', 'useful_join_paths': ['Join with product_store_type to get the type description', 'Join with product_store using parent_id to get the parent category', 'Join with product or service tables to associate products with categories']}
masters.party_job_code - {'qualified_name': 'masters.party_job_code', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'job_code_id', 'references_table': 'public.job_code', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}, {'column': 'party_id', 'references_table': 'public.party', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Linking parties to job codes through time', 'useful_join_paths': ["Join with 'job_code' to get details about the job code", "Join with 'party' to get details about the party", "Join with 'party_job_code' to get historical job code assignments for a party"]}
lms.exam_type - {'qualified_name': 'lms.exam_type', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference', 'useful_join_paths': []}
lms.training_category - {'qualified_name': 'lms.training_category', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference Table', 'useful_join_paths': []}
lms.tm_type - {'qualified_name': 'lms.tm_type', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference', 'useful_join_paths': []}
lms.status - {'qualified_name': 'lms.status', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [{'column': 'category_id', 'references_table': 'public.status_category', 'references_column': 'id', 'relationship_meaning': 'Links this column to the referenced entity.'}], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference table for status definitions', 'useful_join_paths': ["Join with 'status_category' via 'category_id' to get the category context for each status.", "Join with tables that reference 'status' via foreign keys to understand the state of entities."]}
lms.training_type - {'qualified_name': 'lms.training_type', 'primary_keys': [{'column': 'id', 'business_meaning': 'Primary key column that identifies a row in this table.'}], 'foreign_keys': [], 'incoming_foreign_keys': [], 'table_relationship_role': 'Reference Table', 'useful_join_paths': []}

In [23]:
kb_lookup = {}

for table in semantic_kb:

    qualified_name = table.get("qualified_name")

    if qualified_name:
        kb_lookup[qualified_name.lower()] = table

print("Lookup entries:", len(kb_lookup))

Lookup entries: 49

In [24]:
kb_lookup

{'masters.request_type': {'qualified_name': 'masters.request_type',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference table with no direct relationships',
  'useful_join_paths': []},
 'masters.party': {'qualified_name': 'masters.party',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'department_id',
    'references_table': 'public.product_store',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'gender_id',
    'references_table': 'public.gender',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'party_type_id',
    'references_table': 'public.party_type',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'preferred_language_id',
    'references_table': 'public.language',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'qr_code_id',
    'references_table': 'public.qr_code',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'status_id',
    'references_table': 'public.status',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Central entity table with relationships to other entity tables (gender, department, language, etc.)',
  'useful_join_paths': ['Join with public.gender on gender_id to get gender details',
   'Join with public.department on department_id to get department details',
   'Join with public.party_type on party_type_id to get party type details',
   'Join with public.language on preferred_language_id to get language details',
   'Join with public.status on status_id to get status details',
   'Join with public.qr_code on qr_code_id to get QR code details']},
 'masters.security_group_permission': {'qualified_name': 'masters.security_group_permission',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'group_id',
    'references_table': 'public.security_group',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'permission_id',
    'references_table': 'public.permission',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'status_id',
    'references_table': 'public.status',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Central table for linking security groups to permissions through status and validity periods.',
  'useful_join_paths': ['Join with security_group to get group details',
   'Join with permission to get permission details',
   'Join with status to get the current status of the permission assignment']},
 'masters.product_store_user_group': {'qualified_name': 'masters.product_store_user_group',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'party_id',
    'references_table': 'public.party',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'product_store_id',
    'references_table': 'public.product_store',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'user_group_id',
    'references_table': 'public.user_group',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Associates user groups, product stores, and parties',
  'useful_join_paths': ['Join with user_group to get user group details',
   'Join with product_store to get product store details',
   'Join with party to get party details']},
 'masters.sys_persistent_audit_event': {'qualified_name': 'masters.sys_persistent_audit_event',
  'primary_keys': [{'column': 'event_id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Source of audit data',
  'useful_join_paths': []},
 'masters.job_code': {'qualified_name': 'masters.job_code',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'dept_id',
    'references_table': 'public.product_store',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference table for job roles, linked to departments',
  'useful_join_paths': ['Join with product_store on dept_id to get department details',
   'Join with user tables on approved_by_user, returned_by_user, or created_by_user to get user context']},
 'masters.status': {'qualified_name': 'masters.status',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'category_id',
    'references_table': 'public.status_category',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference table for status definitions',
  'useful_join_paths': ['Join with status_category to get the category of a status',
   'Join with entities or other tables that reference status via foreign key']},
 'masters.leave': {'qualified_name': 'masters.leave',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'party_id',
    'references_table': 'public.party',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'type_id',
    'references_table': 'public.leave_type',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Central entity for leave management, linked to employees and leave types',
  'useful_join_paths': ['Join with public.party to get employee details',
   'Join with public.leave_type to get leave type descriptions']},
 'masters.party_type': {'qualified_name': 'masters.party_type',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference table for categorization',
  'useful_join_paths': ['party_type JOIN party ON party.party_type_id = party_type.id']},
 'masters.contact_mech_type': {'qualified_name': 'masters.contact_mech_type',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference table for contact mechanism types',
  'useful_join_paths': []},
 'masters.sys_persistent_audit_evt_data': {'qualified_name': 'masters.sys_persistent_audit_evt_data',
  'primary_keys': [{'column': 'event_id',
    'business_meaning': 'Primary key column that identifies a row in this table.'},
   {'column': 'name',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'event_id',
    'references_table': 'public.sys_persistent_audit_event',
    'references_column': 'event_id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Child Table (Audit Event Data)',
  'useful_join_paths': ["Join with 'sys_persistent_audit_event' on 'event_id' to get event metadata",
   "Join with other tables if 'event_id' is used as a foreign key elsewhere"]},
 'masters.role_type': {'qualified_name': 'masters.role_type',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference',
  'useful_join_paths': []},
 'masters.permission': {'qualified_name': 'masters.permission',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'mod_id',
    'references_table': 'public.mod',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Authorization Definition Table',
  'useful_join_paths': ["Join with 'mod' table via 'mod_id' to understand which module the permission belongs to.",
   "Join with 'user' or 'role' tables (if available) to determine which users or roles have this permission."]},
 'masters.security_group': {'qualified_name': 'masters.security_group',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'mod_id',
    'references_table': 'public.mod',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'status_id',
    'references_table': 'public.status',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Central security entity with relationships to system modules and status definitions.',
  'useful_join_paths': ["Join with 'public.mod' to understand which module this security group belongs to.",
   "Join with 'public.status' to determine the current status of the security group."]},
 'masters.status_category': {'qualified_name': 'masters.status_category',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference table with no direct relationships',
  'useful_join_paths': []},
 'masters.request_history': {'qualified_name': 'masters.request_history',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'from_status_id',
    'references_table': 'public.status',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'request_id',
    'references_table': 'public.request',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'to_status_id',
    'references_table': 'public.status',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Event Log for Request Lifecycle',
  'useful_join_paths': ["Join with 'public.request' to get request details",
   "Join with 'public.status' to get status names",
   "Join with 'public.user' to get user details for 'created_by' and 'last_modified_by'"]},
 'masters.product_store_type': {'qualified_name': 'masters.product_store_type',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference table used to classify store structures or organizational units for products.',
  'useful_join_paths': ['Join with product tables to associate products with store types',
   'Join with store tables to classify store structures']},
 'masters.request': {'qualified_name': 'masters.request',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'approved_by_id',
    'references_table': 'public.party',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'request_type_id',
    'references_table': 'public.request_type',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'reviewed_by_id',
    'references_table': 'public.party',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'status_id',
    'references_table': 'public.status',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Central entity with many-to-one relationships to party, request_type, and status',
  'useful_join_paths': ['Join with party to get approver/reviewer details',
   'Join with request_type to get request category',
   'Join with status to get current status description']},
 'masters.system_parameters': {'qualified_name': 'masters.system_parameters',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'product_id',
    'references_table': 'public.product',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'product_store_id',
    'references_table': 'public.product_store',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference Table for Configuration Parameters',
  'useful_join_paths': ['Join with public.product on product_id to get product-specific context',
   'Join with public.product_store on product_store_id to get store-specific context']},
 'masters.party_role': {'qualified_name': 'masters.party_role',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'party_id',
    'references_table': 'public.party',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'role_type_id',
    'references_table': 'public.role_type',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference table for role assignments',
  'useful_join_paths': ["Join with 'party' to get party details",
   "Join with 'role_type' to get role type definitions"]},
 'masters.user_security_group': {'qualified_name': 'masters.user_security_group',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'party_id',
    'references_table': 'public.party',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'security_group_id',
    'references_table': 'public.security_group',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'status_id',
    'references_table': 'public.status',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'user_group_id',
    'references_table': 'public.user_group',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Central hub for user-to-security-group and user-to-user-group relationships',
  'useful_join_paths': ['Join with public.party to get user details',
   'Join with public.security_group to get security group details',
   'Join with public.user_group to get user group details',
   'Join with public.status to get membership status details']},
 'masters.mod': {'qualified_name': 'masters.mod',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference table with no direct relationships to other tables.',
  'useful_join_paths': []},
 'masters.product_store': {'qualified_name': 'masters.product_store',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'parent_id',
    'references_table': 'public.product_store',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'type_id',
    'references_table': 'public.product_store_type',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Hierarchical and typed categorization of organizational units',
  'useful_join_paths': ['Join with product_store_type to get the type description',
   'Join with product_store using parent_id to get the parent category',
   'Join with product or service tables to associate products with categories']},
 'masters.party_job_code': {'qualified_name': 'masters.party_job_code',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'job_code_id',
    'references_table': 'public.job_code',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'},
   {'column': 'party_id',
    'references_table': 'public.party',
    'references_column': 'id',
    'relationship_meaning': 'Links this column to the referenced entity.'}],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Linking parties to job codes through time',
  'useful_join_paths': ["Join with 'job_code' to get details about the job code",
   "Join with 'party' to get details about the party",
   "Join with 'party_job_code' to get historical job code assignments for a party"]},
 'lms.exam_type': {'qualified_name': 'lms.exam_type',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference',
  'useful_join_paths': []},
 'lms.training_category': {'qualified_name': 'lms.training_category',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference Table',
  'useful_join_paths': []},
 'lms.tm_type': {'qualified_name': 'lms.tm_type',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [],
  'incoming_foreign_keys': [],
  'table_relationship_role': 'Reference',
  'useful_join_paths': []},
 'lms.status': {'qualified_name': 'lms.status',
  'primary_keys': [{'column': 'id',
    'business_meaning': 'Primary key column that identifies a row in this table.'}],
  'foreign_keys': [{'column': 'category_id',
    'references_table': 'public.status_category',

In [25]:
for name in list(kb_lookup.keys()):
    print(name)

masters.request_type
masters.party
masters.security_group_permission
masters.product_store_user_group
masters.sys_persistent_audit_event
masters.job_code
masters.status
masters.leave
masters.party_type
masters.contact_mech_type
masters.sys_persistent_audit_evt_data
masters.role_type
masters.permission
masters.security_group
masters.status_category
masters.request_history
masters.product_store_type
masters.request
masters.system_parameters
masters.party_role
masters.user_security_group
masters.mod
masters.product_store
masters.party_job_code
lms.exam_type
lms.training_category
lms.tm_type
lms.status
lms.training_type
lms.training_schedule
lms.status_category
lms.lms_system_parameters
lms.training
lms.tm_job_code
lms.sys_persistent_audit_event
lms.training_attachment
lms.tm
lms.training_session
lms.training_tm
lms.user_training
lms.exam
lms.tm_attachment
lms.training_session_register
lms.time_logs
lms.lms_attachment
lms.sys_persistent_audit_evt_data
pc.sys_user_authority
pc.sys_authority
pc.sys_user

In [26]:
results

,Table_Name,Table_Description,embeddings,similarity
0,lms.training,Table for storing training modules information...,"[-1.387843370437622, 1.1915342807769775, -3.62...",0.743606
1,lms.tm,Table for storing training module information ...,"[-1.0574955940246582, 1.2831698656082153, -3.7...",0.741871
2,lms.training_attachment,Table for storing attachments like docs pdfs e...,"[-0.6275388598442078, 1.0483890771865845, -3.5...",0.698679
3,lms.user_training,Table for storing user training information fo...,"[-1.0158430337905884, 1.3814443349838257, -3.8...",0.667549
4,lms.tm_attachment,Table for storing attachments like docs pdfs e...,"[-0.3467835783958435, 1.1310498714447021, -3.5...",0.663732

In [27]:
messages = []

for table_name in results["Table_Name"]:

    table_info = kb_lookup.get(table_name.lower())

    if table_info:
        messages.append(
            json.dumps(table_info, indent=2)
        )

message = "\n\n".join(messages)

print(message)

{
  "qualified_name": "lms.training",
  "primary_keys": [
    {
      "column": "id",
      "business_meaning": "Primary key column that identifies a row in this table."
    }
  ],
  "foreign_keys": [
    {
      "column": "category_id",
      "references_table": "public.training_category",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "status_id",
      "references_table": "public.status",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "type_id",
      "references_table": "public.training_type",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    }
  ],
  "incoming_foreign_keys": [],
  "table_relationship_role": "Central entity table with relationships to training categories, statuses, and types.",
  "useful_join_paths": [
    "Join with training_category to get category details",
    "Join with status to get training status",
    "Join with training_type to get training type details",
    "Join with users to get who created or modified the training"
  ]
}

{
  "qualified_name": "lms.tm",
  "primary_keys": [
    {
      "column": "id",
      "business_meaning": "Primary key column that identifies a row in this table."
    }
  ],
  "foreign_keys": [
    {
      "column": "category_id",
      "references_table": "public.training_category",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "status_id",
      "references_table": "public.status",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "tr_type_id",
      "references_table": "public.training_type",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "training_id",
      "references_table": "public.training",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "type_id",
      "references_table": "public.tm_type",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    }
  ],
  "incoming_foreign_keys": [],
  "table_relationship_role": "Primary entity in the training material ecosystem",
  "useful_join_paths": [
    "Join with training_category to get category details",
    "Join with status to get the current status of the training material",
    "Join with training to get related training records",
    "Join with tm_type to get type-specific metadata"
  ]
}

{
  "qualified_name": "lms.training_attachment",
  "primary_keys": [
    {
      "column": "id",
      "business_meaning": "Primary key column that identifies a row in this table."
    }
  ],
  "foreign_keys": [
    {
      "column": "attachment_id",
      "references_table": "public.lms_attachment",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "training_id",
      "references_table": "public.training",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    }
  ],
  "incoming_foreign_keys": [],
  "table_relationship_role": "Linking table between training sessions and their associated attachments.",
  "useful_join_paths": [
    "Join with 'training' to get training details",
    "Join with 'lms_attachment' to get file metadata",
    "Join with 'user' to get creator/modifier information"
  ]
}

{
  "qualified_name": "lms.user_training",
  "primary_keys": [
    {
      "column": "id",
      "business_meaning": "Primary key column that identifies a row in this table."
    }
  ],
  "foreign_keys": [
    {
      "column": "status_id",
      "references_table": "public.status",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "tm_id",
      "references_table": "public.tm",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "training_id",
      "references_table": "public.training",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "training_session_id",
      "references_table": "public.training_session",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "training_tm_id",
      "references_table": "public.training_tm",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "type_id",
      "references_table": "public.training_type",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    }
  ],
  "incoming_foreign_keys": [],
  "table_relationship_role": "Central hub for training activity data",
  "useful_join_paths": [
    "Join with public.training via training_id",
    "Join with public.status via status_id",
    "Join with public.tm via tm_id",
    "Join with public.training_session via training_session_id",
    "Join with public.training_type via type_id"
  ]
}

{
  "qualified_name": "lms.tm_attachment",
  "primary_keys": [
    {
      "column": "id",
      "business_meaning": "Primary key column that identifies a row in this table."
    }
  ],
  "foreign_keys": [
    {
      "column": "attachment_id",
      "references_table": "public.lms_attachment",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    },
    {
      "column": "tm_id",
      "references_table": "public.tm",
      "references_column": "id",
      "relationship_meaning": "Links this column to the referenced entity."
    }
  ],
  "incoming_foreign_keys": [],
  "table_relationship_role": "Linking table between training modules and attachments",
  "useful_join_paths": [
    "Join with 'tm' to get training module details",
    "Join with 'lms_attachment' to get more detailed attachment metadata",
    "Join with 'users' to get creator information"
  ]
}

In [28]:
from collections import defaultdict, deque


def build_fk_graph(kb):

    graph = defaultdict(list)

    for table in kb:

        table_name = (
            table.get("physical_qualified_name")
            or table.get("qualified_name")
        )

        if not table_name:
            continue

        for fk in table.get("foreign_keys", []):

            fk_column = fk.get("column")
            ref_table = fk.get("references_table")
            ref_column = fk.get("references_column")

            if not fk_column or not ref_table or not ref_column:
                continue

            graph[table_name.lower()].append({
                "from_table": table_name,
                "from_column": fk_column,
                "to_table": ref_table,
                "to_column": ref_column,
                "direction": "forward"
            })

            # Add reverse edge
            graph[ref_table.lower()].append({
                "from_table": ref_table,
                "from_column": ref_column,
                "to_table": table_name,
                "to_column": fk_column,
                "direction": "reverse"
            })

    return graph

In [29]:
fk_graph = build_fk_graph(semantic_kb)

In [30]:
fk_graph

defaultdict(list,
            {'masters.party': [{'from_table': 'masters.party',
               'from_column': 'department_id',
               'to_table': 'public.product_store',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.party',
               'from_column': 'gender_id',
               'to_table': 'public.gender',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.party',
               'from_column': 'party_type_id',
               'to_table': 'public.party_type',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.party',
               'from_column': 'preferred_language_id',
               'to_table': 'public.language',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.party',
               'from_column': 'qr_code_id',
               'to_table': 'public.qr_code',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.party',
               'from_column': 'status_id',
               'to_table': 'public.status',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.product_store': [{'from_table': 'public.product_store',
               'from_column': 'id',
               'to_table': 'masters.party',
               'to_column': 'department_id',
               'direction': 'reverse'},
              {'from_table': 'public.product_store',
               'from_column': 'id',
               'to_table': 'masters.product_store_user_group',
               'to_column': 'product_store_id',
               'direction': 'reverse'},
              {'from_table': 'public.product_store',
               'from_column': 'id',
               'to_table': 'masters.job_code',
               'to_column': 'dept_id',
               'direction': 'reverse'},
              {'from_table': 'public.product_store',
               'from_column': 'id',
               'to_table': 'masters.system_parameters',
               'to_column': 'product_store_id',
               'direction': 'reverse'},
              {'from_table': 'public.product_store',
               'from_column': 'id',
               'to_table': 'masters.product_store',
               'to_column': 'parent_id',
               'direction': 'reverse'}],
             'public.gender': [{'from_table': 'public.gender',
               'from_column': 'id',
               'to_table': 'masters.party',
               'to_column': 'gender_id',
               'direction': 'reverse'}],
             'public.party_type': [{'from_table': 'public.party_type',
               'from_column': 'id',
               'to_table': 'masters.party',
               'to_column': 'party_type_id',
               'direction': 'reverse'}],
             'public.language': [{'from_table': 'public.language',
               'from_column': 'id',
               'to_table': 'masters.party',
               'to_column': 'preferred_language_id',
               'direction': 'reverse'}],
             'public.qr_code': [{'from_table': 'public.qr_code',
               'from_column': 'id',
               'to_table': 'masters.party',
               'to_column': 'qr_code_id',
               'direction': 'reverse'}],
             'public.status': [{'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'masters.party',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'masters.security_group_permission',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'masters.security_group',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'masters.request_history',
               'to_column': 'from_status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'masters.request_history',
               'to_column': 'to_status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'masters.request',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'masters.user_security_group',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'lms.training_schedule',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'lms.training',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'lms.tm',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'lms.training_session',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'lms.user_training',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'lms.exam',
               'to_column': 'status_id',
               'direction': 'reverse'},
              {'from_table': 'public.status',
               'from_column': 'id',
               'to_table': 'lms.training_session_register',
               'to_column': 'status_id',
               'direction': 'reverse'}],
             'masters.security_group_permission': [{'from_table': 'masters.security_group_permission',
               'from_column': 'group_id',
               'to_table': 'public.security_group',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.security_group_permission',
               'from_column': 'permission_id',
               'to_table': 'public.permission',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.security_group_permission',
               'from_column': 'status_id',
               'to_table': 'public.status',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.security_group': [{'from_table': 'public.security_group',
               'from_column': 'id',
               'to_table': 'masters.security_group_permission',
               'to_column': 'group_id',
               'direction': 'reverse'},
              {'from_table': 'public.security_group',
               'from_column': 'id',
               'to_table': 'masters.user_security_group',
               'to_column': 'security_group_id',
               'direction': 'reverse'}],
             'public.permission': [{'from_table': 'public.permission',
               'from_column': 'id',
               'to_table': 'masters.security_group_permission',
               'to_column': 'permission_id',
               'direction': 'reverse'}],
             'masters.product_store_user_group': [{'from_table': 'masters.product_store_user_group',
               'from_column': 'party_id',
               'to_table': 'public.party',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.product_store_user_group',
               'from_column': 'product_store_id',
               'to_table': 'public.product_store',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.product_store_user_group',
               'from_column': 'user_group_id',
               'to_table': 'public.user_group',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.party': [{'from_table': 'public.party',
               'from_column': 'id',
               'to_table': 'masters.product_store_user_group',
               'to_column': 'party_id',
               'direction': 'reverse'},
              {'from_table': 'public.party',
               'from_column': 'id',
               'to_table': 'masters.leave',
               'to_column': 'party_id',
               'direction': 'reverse'},
              {'from_table': 'public.party',
               'from_column': 'id',
               'to_table': 'masters.request',
               'to_column': 'approved_by_id',
               'direction': 'reverse'},
              {'from_table': 'public.party',
               'from_column': 'id',
               'to_table': 'masters.request',
               'to_column': 'reviewed_by_id',
               'direction': 'reverse'},
              {'from_table': 'public.party',
               'from_column': 'id',
               'to_table': 'masters.party_role',
               'to_column': 'party_id',
               'direction': 'reverse'},
              {'from_table': 'public.party',
               'from_column': 'id',
               'to_table': 'masters.user_security_group',
               'to_column': 'party_id',
               'direction': 'reverse'},
              {'from_table': 'public.party',
               'from_column': 'id',
               'to_table': 'masters.party_job_code',
               'to_column': 'party_id',
               'direction': 'reverse'}],
             'public.user_group': [{'from_table': 'public.user_group',
               'from_column': 'id',
               'to_table': 'masters.product_store_user_group',
               'to_column': 'user_group_id',
               'direction': 'reverse'},
              {'from_table': 'public.user_group',
               'from_column': 'id',
               'to_table': 'masters.user_security_group',
               'to_column': 'user_group_id',
               'direction': 'reverse'}],
             'masters.job_code': [{'from_table': 'masters.job_code',
               'from_column': 'dept_id',
               'to_table': 'public.product_store',
               'to_column': 'id',
               'direction': 'forward'}],
             'masters.status': [{'from_table': 'masters.status',
               'from_column': 'category_id',
               'to_table': 'public.status_category',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.status_category': [{'from_table': 'public.status_category',
               'from_column': 'id',
               'to_table': 'masters.status',
               'to_column': 'category_id',
               'direction': 'reverse'},
              {'from_table': 'public.status_category',
               'from_column': 'id',
               'to_table': 'lms.status',
               'to_column': 'category_id',
               'direction': 'reverse'}],
             'masters.leave': [{'from_table': 'masters.leave',
               'from_column': 'party_id',
               'to_table': 'public.party',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.leave',
               'from_column': 'type_id',
               'to_table': 'public.leave_type',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.leave_type': [{'from_table': 'public.leave_type',
               'from_column': 'id',
               'to_table': 'masters.leave',
               'to_column': 'type_id',
               'direction': 'reverse'}],
             'masters.sys_persistent_audit_evt_data': [{'from_table': 'masters.sys_persistent_audit_evt_data',
               'from_column': 'event_id',
               'to_table': 'public.sys_persistent_audit_event',
               'to_column': 'event_id',
               'direction': 'forward'}],
             'public.sys_persistent_audit_event': [{'from_table': 'public.sys_persistent_audit_event',
               'from_column': 'event_id',
               'to_table': 'masters.sys_persistent_audit_evt_data',
               'to_column': 'event_id',
               'direction': 'reverse'},
              {'from_table': 'public.sys_persistent_audit_event',
               'from_column': 'event_id',
               'to_table': 'lms.sys_persistent_audit_evt_data',
               'to_column': 'event_id',
               'direction': 'reverse'}],
             'masters.permission': [{'from_table': 'masters.permission',
               'from_column': 'mod_id',
               'to_table': 'public.mod',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.mod': [{'from_table': 'public.mod',
               'from_column': 'id',
               'to_table': 'masters.permission',
               'to_column': 'mod_id',
               'direction': 'reverse'},
              {'from_table': 'public.mod',
               'from_column': 'id',
               'to_table': 'masters.security_group',
               'to_column': 'mod_id',
               'direction': 'reverse'}],
             'masters.security_group': [{'from_table': 'masters.security_group',
               'from_column': 'mod_id',
               'to_table': 'public.mod',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.security_group',
               'from_column': 'status_id',
               'to_table': 'public.status',
               'to_column': 'id',
               'direction': 'forward'}],
             'masters.request_history': [{'from_table': 'masters.request_history',
               'from_column': 'from_status_id',
               'to_table': 'public.status',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.request_history',
               'from_column': 'request_id',
               'to_table': 'public.request',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.request_history',
               'from_column': 'to_status_id',
               'to_table': 'public.status',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.request': [{'from_table': 'public.request',
               'from_column': 'id',
               'to_table': 'masters.request_history',
               'to_column': 'request_id',
               'direction': 'reverse'}],
             'masters.request': [{'from_table': 'masters.request',
               'from_column': 'approved_by_id',
               'to_table': 'public.party',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.request',
               'from_column': 'request_type_id',
               'to_table': 'public.request_type',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.request',
               'from_column': 'reviewed_by_id',
               'to_table': 'public.party',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.request',
               'from_column': 'status_id',
               'to_table': 'public.status',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.request_type': [{'from_table': 'public.request_type',
               'from_column': 'id',
               'to_table': 'masters.request',
               'to_column': 'request_type_id',
               'direction': 'reverse'}],
             'masters.system_parameters': [{'from_table': 'masters.system_parameters',
               'from_column': 'product_id',
               'to_table': 'public.product',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.system_parameters',
               'from_column': 'product_store_id',
               'to_table': 'public.product_store',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.product': [{'from_table': 'public.product',
               'from_column': 'id',
               'to_table': 'masters.system_parameters',
               'to_column': 'product_id',
               'direction': 'reverse'}],
             'masters.party_role': [{'from_table': 'masters.party_role',
               'from_column': 'party_id',
               'to_table': 'public.party',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.party_role',
               'from_column': 'role_type_id',
               'to_table': 'public.role_type',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.role_type': [{'from_table': 'public.role_type',
               'from_column': 'id',
               'to_table': 'masters.party_role',
               'to_column': 'role_type_id',
               'direction': 'reverse'}],
             'masters.user_security_group': [{'from_table': 'masters.user_security_group',
               'from_column': 'party_id',
               'to_table': 'public.party',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.user_security_group',
               'from_column': 'security_group_id',
               'to_table': 'public.security_group',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.user_security_group',
               'from_column': 'status_id',
               'to_table': 'public.status',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.user_security_group',
               'from_column': 'user_group_id',
               'to_table': 'public.user_group',
               'to_column': 'id',
               'direction': 'forward'}],
             'masters.product_store': [{'from_table': 'masters.product_store',
               'from_column': 'parent_id',
               'to_table': 'public.product_store',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.product_store',
               'from_column': 'type_id',
               'to_table': 'public.product_store_type',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.product_store_type': [{'from_table': 'public.product_store_type',
               'from_column': 'id',
               'to_table': 'masters.product_store',
               'to_column': 'type_id',
               'direction': 'reverse'}],
             'masters.party_job_code': [{'from_table': 'masters.party_job_code',
               'from_column': 'job_code_id',
               'to_table': 'public.job_code',
               'to_column': 'id',
               'direction': 'forward'},
              {'from_table': 'masters.party_job_code',
               'from_column': 'party_id',
               'to_table': 'public.party',
               'to_column': 'id',
               'direction': 'forward'}],
             'public.job_code': [{'from_table': 'public.job_code',
               'from_column': 'id',
               'to_table': 'masters.party_job_code',
               'to_column': 'job_code_id',

In [31]:
def trace_relationships(
    start_tables,
    fk_graph,
    max_depth=3
):

    visited = set()
    queue = deque()

    discovered = []

    for table in start_tables:

        key = table.lower()

        if key not in visited:

            visited.add(key)

            queue.append(
                (table, 0)
            )

    while queue:

        current_table, depth = queue.popleft()

        discovered.append({
            "table": current_table,
            "depth": depth
        })

        if depth >= max_depth:
            continue

        current_key = current_table.lower()

        for edge in fk_graph.get(
            current_key,
            []
        ):

            next_table = edge["to_table"]

            next_key = next_table.lower()

            if next_key not in visited:

                visited.add(next_key)

                queue.append(
                    (
                        next_table,
                        depth + 1
                    )
                )

    return discovered

In [32]:
start_tables = results["Table_Name"].iloc[0:1].to_list()

discovered = trace_relationships(
    start_tables,
    fk_graph,
    max_depth=3
)

for item in discovered:
    print(
        item["depth"],
        item["table"]
    )

0 lms.training
1 public.training_category
1 public.status
1 public.training_type
2 lms.lms_system_parameters
2 lms.tm
2 masters.party
2 masters.security_group_permission
2 masters.security_group
2 masters.request_history
2 masters.request
2 masters.user_security_group
2 lms.training_schedule
2 lms.training_session
2 lms.user_training
2 lms.exam
2 lms.training_session_register
3 public.training
3 public.tm_type
3 public.product_store
3 public.gender
3 public.party_type
3 public.language
3 public.qr_code
3 public.security_group
3 public.permission
3 public.mod
3 public.request
3 public.party
3 public.request_type
3 public.user_group
3 public.training_session_type
3 public.tm
3 public.training_session
3 public.training_tm
3 public.exam_type
3 public.user_training

In [33]:
def get_relevant_tables_from_question(
    question,
    related_tables,
    semantic_kb
):

    question_lower = question.lower()

    relevant = []

    for table in semantic_kb:

        table_name = (
            table.get("physical_qualified_name")
            or table.get("qualified_name")
            or ""
        )

        if table_name.lower() not in [
            t.lower() for t in related_tables
        ]:
            continue

        text = " ".join([
            table_name,
            table.get("table_relationship_role", ""),
            " ".join(table.get("useful_join_paths", []))
        ]).lower()

        # Very simple initial matching
        question_words = question_lower.split()

        score = sum(
            1
            for word in question_words
            if len(word) > 2 and word in text
        )

        if score > 0:
            relevant.append({
                "table": table_name,
                "score": score
            })

    relevant.sort(
        key=lambda x: x["score"],
        reverse=True
    )

    return relevant

In [34]:
get_relevant_tables_from_question(question, results["Table_Name"], semantic_kb)

[{'table': 'lms.training', 'score': 1},
 {'table': 'lms.training_attachment', 'score': 1},
 {'table': 'lms.tm_attachment', 'score': 1}]

In [35]:
question

'List all Trainings SOPs and other all  '

In [36]:
def build_qwen_schema_context(
    candidate_tables,
    semantic_kb
):

    lookup = {}

    for table in semantic_kb:

        name = (
            table.get("physical_qualified_name")
            or table.get("qualified_name")
        )

        if name:
            lookup[name.lower()] = table

    context = []

    for item in candidate_tables:

        table_name = item["table"]
        score = item["score"]

        table = lookup.get(
            table_name.lower()
        )

        if not table:
            continue

        context.append({
            "table": table_name,
            "embedding_score": score,
            "schema": table
        })

    return json.dumps(
        context,
        indent=2,
        ensure_ascii=False
    )

In [37]:
relevant_tables = get_relevant_tables_from_question(question, results["Table_Name"].iloc[0:2].to_list(), semantic_kb)

In [38]:
build_qwen_schema_context(relevant_tables, semantic_kb)

'[\n  {\n    "table": "lms.training",\n    "embedding_score": 1,\n    "schema": {\n      "qualified_name": "lms.training",\n      "primary_keys": [\n        {\n          "column": "id",\n          "business_meaning": "Primary key column that identifies a row in this table."\n        }\n      ],\n      "foreign_keys": [\n        {\n          "column": "category_id",\n          "references_table": "public.training_category",\n          "references_column": "id",\n          "relationship_meaning": "Links this column to the referenced entity."\n        },\n        {\n          "column": "status_id",\n          "references_table": "public.status",\n          "references_column": "id",\n          "relationship_meaning": "Links this column to the referenced entity."\n        },\n        {\n          "column": "type_id",\n          "references_table": "public.training_type",\n          "references_column": "id",\n          "relationship_meaning": "Links this column to the referenced entity."\n        }\n      ],\n      "incoming_foreign_keys": [],\n      "table_relationship_role": "Central entity table with relationships to training categories, statuses, and types.",\n      "useful_join_paths": [\n        "Join with training_category to get category details",\n        "Join with status to get training status",\n        "Join with training_type to get training type details",\n        "Join with users to get who created or modified the training"\n      ]\n    }\n  }\n]'

In [39]:
question

'List all Trainings SOPs and other all  '

## Prototype: hybrid semantic + lexical anchor retrieval

Reuses the finalized graph/bridge/lookup/context machinery from
`lms_chatbot.retrieval` (already built and in production) and only
prototypes the one new piece we're testing here: **anchor selection**
that combines embedding similarity (semantic, always on - handles
paraphrased questions with no literal table/column names) with a
lexical term-overlap score (a boost/rescue signal for when the user's
words happen to match a table name, business term, or column - never
a requirement, since we can't expect users to know exact entity names).

If this looks right across the test questions below, this scoring
function moves into `lms_chatbot/retrieval/embeddings.py` and
`pipeline.py` gets updated to call it instead of pure cosine ranking.

In [40]:
import sys

REPO_ROOT = base.parent  # d:\P_PC_CHATBOT
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from lms_chatbot.retrieval import classify, context as context_mod, graph as graph_mod
from lms_chatbot.retrieval.embeddings import cosine_similarity, get_embedder
from lms_chatbot.retrieval.build_index import _embedding_text

print("Imported production retrieval modules from:", REPO_ROOT)

Imported production retrieval modules from: D:\P_PC_CHATBOT

In [41]:
# Reload the FULL kb fresh - the `semantic_kb` variable above was stripped
# down to only a few fields earlier in this notebook (cell 63b24350) and
# no longer has business_terms/columns/etc. we need for lexical matching.
with open(SEMANTIC_KB_PATH, "r", encoding="utf-8") as f:
    full_kb = json.load(f)

anchors, lookups = classify.split_tables(full_kb)

kb_lookup = {}
for table in full_kb:
    name = classify.table_name(table)
    if name:
        kb_lookup[name.lower()] = table

name_index = classify.NameIndex(full_kb)
fk_graph = graph_mod.build_fk_graph(full_kb, name_index)

print(f"Loaded {len(full_kb)} tables total: {len(anchors)} anchors, {len(lookups)} lookups")

Loaded 49 tables total: 33 anchors, 16 lookups

In [42]:
# Embed every anchor's business description ONCE (this is what
# lms_chatbot.retrieval.build_index does as an offline step). Query time
# below only ever embeds the *question*, never re-embeds table text -
# fixing the per-query re-embed the earlier cells in this notebook did.
embedder = get_embedder()

anchor_names = []
anchor_texts = []

for table in anchors:
    text = _embedding_text(table)
    if text:
        anchor_names.append(classify.table_name(table))
        anchor_texts.append(text)

anchor_vectors = dict(zip(anchor_names, embedder.embed_documents(anchor_texts)))

print(f"Embedded {len(anchor_vectors)} anchor tables")

Embedded 33 anchor tables

In [43]:
import re

_STOPWORDS = {
    "the", "a", "an", "is", "are", "was", "were", "and", "or", "of", "in",
    "on", "to", "for", "by", "with", "all", "list", "show", "get", "find",
    "what", "which", "who", "that", "this", "these", "those", "me",
    "please", "give", "display", "tell", "want", "need", "can", "you",
    "does", "do", "did", "has", "have", "had", "not", "any",
}


def tokenize(text: str) -> set[str]:
    words = re.findall(r"[a-z0-9]+", text.lower())
    return {w for w in words if len(w) > 2 and w not in _STOPWORDS}


def build_lexical_bag(table: dict) -> set[str]:
    """Bag of literal terms a user might type that should point at this table -
    table/column names, business terms, aliases, column synonyms - as opposed
    to embedding text, which is full descriptive prose for semantic matching."""

    parts = []

    for key in ("business_name", "table_name", "qualified_name", "physical_qualified_name"):
        value = table.get(key)
        if value:
            parts.append(value)

    parts.extend(table.get("business_terms") or [])
    parts.extend(table.get("aliases") or [])
    parts.extend(table.get("related_business_concepts") or [])
    parts.extend(table.get("likely_user_phrases") or [])

    for column in table.get("columns") or []:
        if column.get("column_name"):
            parts.append(column["column_name"])
        parts.extend(column.get("synonyms") or [])
        parts.extend(column.get("likely_user_terms") or [])

    bag: set[str] = set()
    for part in parts:
        bag |= tokenize(part)

    return bag


lexical_index = {
    classify.table_name(table): build_lexical_bag(table)
    for table in anchors
    if classify.table_name(table)
}

print(f"Built lexical bags for {len(lexical_index)} anchor tables")

Built lexical bags for 33 anchor tables

In [44]:
# Semantic is the primary signal and always runs (handles paraphrases with
# zero literal table/column names). Lexical is a BOOST, never a gate: a
# table with no lexical overlap at all can still win purely on semantic
# similarity; lexical only pushes a table up (or in) when the user's words
# happen to match its name/terms/columns.
LEXICAL_BOOST = 0.5


def lexical_score(question_tokens: set[str], bag: set[str]) -> float:
    if not question_tokens or not bag:
        return 0.0
    return len(question_tokens & bag) / len(question_tokens)


def hybrid_anchor_scores(question: str, top_n: int):
    question_tokens = tokenize(question)
    query_vector = embedder.embed_query(question)

    scored = []
    for name, vector in anchor_vectors.items():
        semantic = cosine_similarity(query_vector, vector)
        lexical = lexical_score(question_tokens, lexical_index.get(name, set()))
        final = semantic + LEXICAL_BOOST * lexical
        scored.append({
            "table": name,
            "final": final,
            "semantic": semantic,
            "lexical": lexical,
        })

    scored.sort(key=lambda row: row["final"], reverse=True)
    return scored[:top_n]


def get_relevant_schema_prototype(question, top_n=6, max_tables=14, bridge_max_hops=4):
    scored_anchors = hybrid_anchor_scores(question, top_n)
    anchor_names_selected = [row["table"] for row in scored_anchors]

    bridges = sorted(
        graph_mod.bridge_tables(fk_graph, anchor_names_selected, bridge_max_hops)
        - {a.lower() for a in anchor_names_selected}
    )

    core = anchor_names_selected + bridges
    lookup_names = sorted(
        graph_mod.attach_lookups(kb_lookup, name_index, core, classify.is_lookup_table)
        - {c.lower() for c in core}
    )

    selected = (
        [(name, "anchor") for name in anchor_names_selected]
        + [(name, "bridge") for name in bridges]
        + [(name, "lookup") for name in lookup_names]
    )[:max_tables]

    tables_with_roles = []
    for name, role in selected:
        entry = kb_lookup.get(name.lower())
        if entry:
            tables_with_roles.append((entry, role))

    return {
        "question": question,
        "scored_anchors": scored_anchors,
        "anchors": anchor_names_selected,
        "bridges": bridges,
        "lookups": lookup_names,
        "total_tables": len(tables_with_roles),
        "context": context_mod.render_context(tables_with_roles, name_index),
    }

In [45]:
test_questions = [
    # 1. Pure paraphrase, no literal table/column names - semantic must carry this alone.
    "who has completed their training",
    # 2. Literal table name mention - lexical should boost/rescue this.
    "show me tm_attachment files",
    # 3. Multi-entity question - two anchors should surface, bridged correctly.
    "list all trainings and their categories",
    # 4. Different domain (masters.*, not lms.*) - checks anchors stay scoped,
    #    no leakage into unrelated hub tables (gender, qr_code, language, ...).
    "which security group does a user belong to",
]

for q in test_questions:
    result = get_relevant_schema_prototype(q)

    print("=" * 100)
    print("Q:", result["question"])
    print(f"-> {result['total_tables']} tables total "
          f"({len(result['anchors'])} anchor, {len(result['bridges'])} bridge, {len(result['lookups'])} lookup)")
    print()
    print("Anchor scores (table | final | semantic | lexical):")
    for row in result["scored_anchors"]:
        print(f"  {row['table']:<30} {row['final']:.3f}   {row['semantic']:.3f}   {row['lexical']:.3f}")
    print()
    print("Bridges:", result["bridges"] or "(none)")
    print("Lookups:", result["lookups"] or "(none)")
    print()
    print(result["context"])
    print()

====================================================================================================
Q: who has completed their training
-> 10 tables total (6 anchor, 1 bridge, 3 lookup)

Anchor scores (table | final | semantic | lexical):
  lms.user_training              1.012   0.679   0.667
  lms.training_schedule          0.832   0.666   0.333
  lms.training_session_register  0.813   0.647   0.333
  lms.training                   0.804   0.637   0.333
  lms.training_session           0.796   0.629   0.333
  masters.party                  0.787   0.454   0.667

Bridges: ['masters.status']
Lookups: ['lms.status', 'masters.party_type', 'masters.status_category']

TABLE lms.user_training (anchor)
PURPOSE: This table captures detailed records of user training activities, including training sessions, performance metrics, and administrative information.
COLUMNS: id BIGINT, from_date TIMESTAMP WITHOUT TIME ZONE, thru_date TIMESTAMP WITHOUT TIME ZONE, marks DOUBLE PRECISION, percentage DOUBLE PRECISION, start_time TIMESTAMP WITHOUT TIME ZONE, end_time TIMESTAMP WITHOUT TIME ZONE, info TEXT, remarks VARCHAR(255), attend_count INTEGER, require_exam BOOLEAN, logbook_no VARCHAR(255), read_time BIGINT, party_id BIGINT, emp_id VARCHAR(255), supervisor VARCHAR(255), user_dept VARCHAR(255), tr_dept VARCHAR(255), init_sop_tr BOOLEAN, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, training_id BIGINT, tm_id BIGINT, training_tm_id BIGINT, type_id BIGINT, training_session_id BIGINT, status_id BIGINT
JOINS:
  status_id -> masters.status/lms.status.id
  tm_id -> lms.tm.id
  training_id -> lms.training.id
  training_session_id -> lms.training_session.id
  training_tm_id -> lms.training_tm.id
  type_id -> lms.training_type.id

TABLE lms.training_schedule (anchor)
PURPOSE: A record of planned, proposed, and actual training sessions within the learning management system.
COLUMNS: id BIGINT, name VARCHAR(60), start_time TIMESTAMP WITHOUT TIME ZONE, end_time TIMESTAMP WITHOUT TIME ZONE, alert_time TIMESTAMP WITHOUT TIME ZONE, tolerance_time TIMESTAMP WITHOUT TIME ZONE, actual_start_time TIMESTAMP WITHOUT TIME ZONE, actual_end_time TIMESTAMP WITHOUT TIME ZONE, proposed_start_time TIMESTAMP WITHOUT TIME ZONE, proposed_end_time TIMESTAMP WITHOUT TIME ZONE, info TEXT, remarks VARCHAR(255), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, training_id BIGINT, status_id BIGINT
JOINS:
  status_id -> masters.status/lms.status.id
  training_id -> lms.training.id

TABLE lms.training_session_register (anchor)
PURPOSE: This table records the registration details of trainees for specific training sessions, including session details, trainee participation, and status tracking.
COLUMNS: id BIGINT, name VARCHAR(255), start_time TIMESTAMP WITHOUT TIME ZONE, end_time TIMESTAMP WITHOUT TIME ZONE, attended BOOLEAN, exam_result VARCHAR(255), remarks VARCHAR(255), registration_time TIMESTAMP WITHOUT TIME ZONE, cancelled_time TIMESTAMP WITHOUT TIME ZONE, trainee_id BIGINT, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, training_session_id BIGINT, ut_id BIGINT, status_id BIGINT
JOINS:
  status_id -> masters.status/lms.status.id
  training_session_id -> lms.training_session.id
  ut_id -> lms.user_training.id

TABLE lms.training (anchor)
PURPOSE: A repository of training programs, courses, and related metadata for an enterprise learning management system.
COLUMNS: id BIGINT, name VARCHAR(1500), description VARCHAR(1500), doc_ref_no VARCHAR(1500), sequence_no INTEGER, training_hours INTEGER, training_mins INTEGER, training_days INTEGER, training_months INTEGER, require_exam BOOLEAN, no_of_questions INTEGER, exam_questions INTEGER, correct_answers_required INTEGER, schedule TEXT, questions TEXT, jobcodes TEXT, from_date TIMESTAMP WITHOUT TIME ZONE, thru_date TIMESTAMP WITHOUT TIME ZONE, start_date TIMESTAMP WITHOUT TIME ZONE, end_date TIMESTAMP WITHOUT TIME ZONE, is_exam_online BOOLEAN, remarks VARCHAR(255), dept_id BIGINT, dept_name VARCHAR(255), qr_code_id BIGINT, parent VARCHAR(255), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, category_id BIGINT, type_id BIGINT, status_id BIGINT
JOINS:
  category_id -> lms.training_category.id
  status_id -> masters.status/lms.status.id
  type_id -> lms.training_type.id

TABLE lms.training_session (anchor)
PURPOSE: A record representing a specific instance of a training event or session conducted within the Learning Management System (LMS).
COLUMNS: id BIGINT, name VARCHAR(255), from_date TIMESTAMP WITHOUT TIME ZONE, thru_date TIMESTAMP WITHOUT TIME ZONE, actual_start_time TIMESTAMP WITHOUT TIME ZONE, actual_end_time TIMESTAMP WITHOUT TIME ZONE, training_hall VARCHAR(24), training_hall_capacity INTEGER, is_online BOOLEAN, remarks VARCHAR(255), trainer_id BIGINT, trainer VARCHAR(255), facility_id BIGINT, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, training_id BIGINT, status_id BIGINT, ut_id BIGINT, ts_type_id BIGINT
JOINS:
  status_id -> masters.status/lms.status.id
  training_id -> lms.training.id
  ts_type_id -> public.training_session_type [unverified].id

TABLE masters.party (anchor)
PURPOSE: A central entity representing individuals or entities (such as users, employees, or customers) within the system.
COLUMNS: id BIGINT, first_name VARCHAR(100), last_name VARCHAR(100), display_name VARCHAR(100), profile_picture OID, profile_picture_content_type VARCHAR(255), email VARCHAR(75), birthdate TIMESTAMP WITHOUT TIME ZONE, notes VARCHAR(255), mobile_number VARCHAR(14), date_of_joining TIMESTAMP WITHOUT TIME ZONE, training_completed_date TIMESTAMP WITHOUT TIME ZONE, jd_approved_on TIMESTAMP WITHOUT TIME ZONE, is_temporary_password BOOLEAN, employee_id VARCHAR(255), auth_string TEXT, user_group_string TEXT, require_induction BOOLEAN, nature_of_intro VARCHAR(25), exp VARCHAR(2), total_exp VARCHAR(2), on_long_leave BOOLEAN, leave_date DATE, rejoin_date DATE, login_attempts INTEGER, reset_remarks VARCHAR(60), reactivate_time TIMESTAMP WITHOUT TIME ZONE, force_password_change TIMESTAMP WITHOUT TIME ZONE, prev_emp TEXT, education TEXT, token VARCHAR(255), ip VARCHAR(255), session_id VARCHAR(255), exit_date DATE, reset_by_user_id BIGINT, user_id BIGINT, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, status_id BIGINT, party_type_id BIGINT, preferred_language_id BIGINT, gender_id BIGINT, department_id BIGINT, qr_code_id BIGINT, require_ojt BOOLEAN
JOINS:
  department_id -> masters.product_store.id
  gender_id -> public.gender [unverified].id
  party_type_id -> masters.party_type.id
  preferred_language_id -> public.language [unverified].id
  qr_code_id -> public.qr_code [unverified].id
  status_id -> masters.status/lms.status.id

TABLE masters.status (bridge)
PURPOSE: A table that defines the status values used across the system to represent the lifecycle or condition of entities.
COLUMNS: id BIGINT, name VARCHAR(60), sequence_no INTEGER, description VARCHAR(100), type VARCHAR(60), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, category_id BIGINT
JOINS:
  category_id -> masters.status_category/lms.status_category.id

TABLE lms.status (lookup)
PURPOSE: A table that defines the status values used across the learning management system (LMS) to represent the current state of entities such as courses, enrollments, or tasks.
COLUMNS: id BIGINT, name VARCHAR(60), sequence_no INTEGER, description VARCHAR(100), type VARCHAR(60), category_id BIGINT
JOINS:
  category_id -> masters.status_category/lms.status_category.id

TABLE masters.party_type (lookup)
PURPOSE: A classification system for categorizing different types of parties in the system.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(255)

TABLE masters.status_category (lookup)
PURPOSE: A classification system used to categorize the status of entities within an enterprise system.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(100), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE

====================================================================================================
Q: show me tm_attachment files
-> 13 tables total (6 anchor, 3 bridge, 4 lookup)

Anchor scores (table | final | semantic | lexical):
  lms.tm_attachment              1.044   0.794   0.500
  lms.lms_attachment             0.961   0.711   0.500
  lms.tm                         0.808   0.558   0.500
  masters.request                0.458   0.458   0.000
  lms.lms_system_parameters      0.444   0.444   0.000
  lms.training                   0.441   0.441   0.000

Bridges: ['lms.training_attachment', 'lms.training_category', 'masters.status']
Lookups: ['lms.status', 'lms.tm_type', 'masters.request_type', 'masters.status_category']

TABLE lms.tm_attachment (anchor)
PURPOSE: A table that stores metadata and references for attachments associated with training modules (tm) and other attachment entities.
COLUMNS: id BIGINT, attachment_name VARCHAR(255), description VARCHAR(255), attachment_type VARCHAR(60), ext_id VARCHAR(255), content_type VARCHAR(255), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, tm_id BIGINT, attachment_id BIGINT
JOINS:
  attachment_id -> lms.lms_attachment.id
  tm_id -> lms.tm.id

TABLE lms.lms_attachment (anchor)
PURPOSE: A table that stores metadata and file information for attachments uploaded to the Learning Management System (LMS).
COLUMNS: id BIGINT, name VARCHAR(255), file_attachment OID, file_attachment_content_type VARCHAR(255), attachment_url VARCHAR(255), mime_type VARCHAR(255)

TABLE lms.tm (anchor)
PURPOSE: The `tm` table represents training materials or courses within a Learning Management System (LMS). It stores metadata about each training material, including its name, description, duration, exam requirements, and associated departments and statuses.
COLUMNS: id BIGINT, name VARCHAR(1500), sequence_no INTEGER, description VARCHAR(1500), training_duration BIGINT, training_hours INTEGER, training_mins INTEGER, training_days INTEGER, training_months INTEGER, require_exam BOOLEAN, no_of_questions INTEGER, correct_answers_required INTEGER, exam_questions INTEGER, questions TEXT, jobcodes TEXT, info TEXT, attachment_url VARCHAR(255), is_sop BOOLEAN, sop_number VARCHAR(255), version INTEGER, effective_date DATE, planned_date DATE, thru_date DATE, prev_sop BIGINT, dept_id BIGINT, dept_name VARCHAR(255), legacy VARCHAR(255), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, training_id BIGINT, category_id BIGINT, type_id BIGINT, tr_type_id BIGINT, status_id BIGINT
JOINS:
  category_id -> lms.training_category.id
  status_id -> masters.status/lms.status.id
  tr_type_id -> lms.training_type.id
  training_id -> lms.training.id
  type_id -> lms.tm_type.id

TABLE masters.request (anchor)
PURPOSE: A record representing a request made within an enterprise system, including its status, type, and associated users.
COLUMNS: id BIGINT, name VARCHAR(255), info TEXT, comments VARCHAR(255), reviewed_time TIMESTAMP WITHOUT TIME ZONE, approved_time TIMESTAMP WITHOUT TIME ZONE, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, request_type_id BIGINT, reviewed_by_id BIGINT, approved_by_id BIGINT, status_id BIGINT
JOINS:
  approved_by_id -> masters.party.id
  request_type_id -> masters.request_type.id
  reviewed_by_id -> masters.party.id
  status_id -> masters.status/lms.status.id

TABLE lms.lms_system_parameters (anchor)
PURPOSE: A table that stores system-level configuration parameters used by the Learning Management System (LMS). These parameters define operational settings, flags, and values that control various system behaviors.
COLUMNS: id BIGINT, name VARCHAR(255), info VARCHAR(500), value VARCHAR(255), dept_id BIGINT, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, training_id BIGINT, category_id BIGINT
JOINS:
  category_id -> lms.training_category.id
  training_id -> lms.training.id

TABLE lms.training (anchor)
PURPOSE: A repository of training programs, courses, and related metadata for an enterprise learning management system.
COLUMNS: id BIGINT, name VARCHAR(1500), description VARCHAR(1500), doc_ref_no VARCHAR(1500), sequence_no INTEGER, training_hours INTEGER, training_mins INTEGER, training_days INTEGER, training_months INTEGER, require_exam BOOLEAN, no_of_questions INTEGER, exam_questions INTEGER, correct_answers_required INTEGER, schedule TEXT, questions TEXT, jobcodes TEXT, from_date TIMESTAMP WITHOUT TIME ZONE, thru_date TIMESTAMP WITHOUT TIME ZONE, start_date TIMESTAMP WITHOUT TIME ZONE, end_date TIMESTAMP WITHOUT TIME ZONE, is_exam_online BOOLEAN, remarks VARCHAR(255), dept_id BIGINT, dept_name VARCHAR(255), qr_code_id BIGINT, parent VARCHAR(255), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, category_id BIGINT, type_id BIGINT, status_id BIGINT
JOINS:
  category_id -> lms.training_category.id
  status_id -> masters.status/lms.status.id
  type_id -> lms.training_type.id

TABLE lms.training_attachment (bridge)
PURPOSE: A table that stores information about attachments related to training sessions within the Learning Management System (LMS).
COLUMNS: id BIGINT, attachment_name VARCHAR(255), description VARCHAR(255), attachment_type VARCHAR(60), ext_id VARCHAR(255), content_type VARCHAR(255), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, training_id BIGINT, attachment_id BIGINT, training_duration BIGINT, training_hours INTEGER, training_mins INTEGER
JOINS:
  attachment_id -> lms.lms_attachment.id
  training_id -> lms.training.id

TABLE lms.training_category (bridge)
PURPOSE: A classification system for categorizing different types of training programs within an organization.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(100)

TABLE masters.status (bridge)
PURPOSE: A table that defines the status values used across the system to represent the lifecycle or condition of entities.
COLUMNS: id BIGINT, name VARCHAR(60), sequence_no INTEGER, description VARCHAR(100), type VARCHAR(60), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, category_id BIGINT
JOINS:
  category_id -> masters.status_category/lms.status_category.id

TABLE lms.status (lookup)
PURPOSE: A table that defines the status values used across the learning management system (LMS) to represent the current state of entities such as courses, enrollments, or tasks.
COLUMNS: id BIGINT, name VARCHAR(60), sequence_no INTEGER, description VARCHAR(100), type VARCHAR(60), category_id BIGINT
JOINS:
  category_id -> masters.status_category/lms.status_category.id

TABLE lms.tm_type (lookup)
PURPOSE: This table defines the different types of training available within the Learning Management System (LMS).
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(255)

TABLE masters.request_type (lookup)
PURPOSE: A classification of different types of requests that users or systems can submit within an application or system.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(100), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE

TABLE masters.status_category (lookup)
PURPOSE: A classification system used to categorize the status of entities within an enterprise system.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(100), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE

====================================================================================================
Q: list all trainings and their categories
-> 12 tables total (6 anchor, 2 bridge, 4 lookup)

Anchor scores (table | final | semantic | lexical):
  lms.training_category          1.000   0.833   0.333
  lms.status_category            0.895   0.729   0.333
  lms.training_type              0.766   0.766   0.000
  masters.product_store          0.723   0.556   0.333
  lms.user_training              0.698   0.698   0.000
  lms.training                   0.684   0.684   0.000

Bridges: ['masters.party', 'masters.status']
Lookups: ['lms.status', 'masters.party_type', 'masters.product_store_type', 'masters.status_category']

TABLE lms.training_category (anchor)
PURPOSE: A classification system for categorizing different types of training programs within an organization.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(100)

TABLE lms.status_category (anchor)
PURPOSE: A classification system that categorizes different types of status entries within a learning management system.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(100)

TABLE lms.training_type (anchor)
PURPOSE: This table defines the different types of training available within the learning management system, including their characteristics such as whether they require exams, and whether the exam or training is conducted online.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(100), require_exam BOOLEAN, exam_online BOOLEAN, training_online BOOLEAN

TABLE masters.product_store (anchor)
PURPOSE: A hierarchical structure representing different categories or departments within an organization, such as Engineering Services, Safety Health and Environment, and Human Resources and Administration.
COLUMNS: id BIGINT, name VARCHAR(100), title VARCHAR(100), subtitle VARCHAR(255), image_url VARCHAR(255), require_induction BOOLEAN, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, type_id BIGINT, parent_id BIGINT
JOINS:
  parent_id -> masters.product_store.id
  type_id -> masters.product_store_type.id

TABLE lms.user_training (anchor)
PURPOSE: This table captures detailed records of user training activities, including training sessions, performance metrics, and administrative information.
COLUMNS: id BIGINT, from_date TIMESTAMP WITHOUT TIME ZONE, thru_date TIMESTAMP WITHOUT TIME ZONE, marks DOUBLE PRECISION, percentage DOUBLE PRECISION, start_time TIMESTAMP WITHOUT TIME ZONE, end_time TIMESTAMP WITHOUT TIME ZONE, info TEXT, remarks VARCHAR(255), attend_count INTEGER, require_exam BOOLEAN, logbook_no VARCHAR(255), read_time BIGINT, party_id BIGINT, emp_id VARCHAR(255), supervisor VARCHAR(255), user_dept VARCHAR(255), tr_dept VARCHAR(255), init_sop_tr BOOLEAN, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, training_id BIGINT, tm_id BIGINT, training_tm_id BIGINT, type_id BIGINT, training_session_id BIGINT, status_id BIGINT
JOINS:
  status_id -> masters.status/lms.status.id
  tm_id -> lms.tm.id
  training_id -> lms.training.id
  training_session_id -> lms.training_session.id
  training_tm_id -> lms.training_tm.id
  type_id -> lms.training_type.id

TABLE lms.training (anchor)
PURPOSE: A repository of training programs, courses, and related metadata for an enterprise learning management system.
COLUMNS: id BIGINT, name VARCHAR(1500), description VARCHAR(1500), doc_ref_no VARCHAR(1500), sequence_no INTEGER, training_hours INTEGER, training_mins INTEGER, training_days INTEGER, training_months INTEGER, require_exam BOOLEAN, no_of_questions INTEGER, exam_questions INTEGER, correct_answers_required INTEGER, schedule TEXT, questions TEXT, jobcodes TEXT, from_date TIMESTAMP WITHOUT TIME ZONE, thru_date TIMESTAMP WITHOUT TIME ZONE, start_date TIMESTAMP WITHOUT TIME ZONE, end_date TIMESTAMP WITHOUT TIME ZONE, is_exam_online BOOLEAN, remarks VARCHAR(255), dept_id BIGINT, dept_name VARCHAR(255), qr_code_id BIGINT, parent VARCHAR(255), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, category_id BIGINT, type_id BIGINT, status_id BIGINT
JOINS:
  category_id -> lms.training_category.id
  status_id -> masters.status/lms.status.id
  type_id -> lms.training_type.id

TABLE masters.party (bridge)
PURPOSE: A central entity representing individuals or entities (such as users, employees, or customers) within the system.
COLUMNS: id BIGINT, first_name VARCHAR(100), last_name VARCHAR(100), display_name VARCHAR(100), profile_picture OID, profile_picture_content_type VARCHAR(255), email VARCHAR(75), birthdate TIMESTAMP WITHOUT TIME ZONE, notes VARCHAR(255), mobile_number VARCHAR(14), date_of_joining TIMESTAMP WITHOUT TIME ZONE, training_completed_date TIMESTAMP WITHOUT TIME ZONE, jd_approved_on TIMESTAMP WITHOUT TIME ZONE, is_temporary_password BOOLEAN, employee_id VARCHAR(255), auth_string TEXT, user_group_string TEXT, require_induction BOOLEAN, nature_of_intro VARCHAR(25), exp VARCHAR(2), total_exp VARCHAR(2), on_long_leave BOOLEAN, leave_date DATE, rejoin_date DATE, login_attempts INTEGER, reset_remarks VARCHAR(60), reactivate_time TIMESTAMP WITHOUT TIME ZONE, force_password_change TIMESTAMP WITHOUT TIME ZONE, prev_emp TEXT, education TEXT, token VARCHAR(255), ip VARCHAR(255), session_id VARCHAR(255), exit_date DATE, reset_by_user_id BIGINT, user_id BIGINT, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, status_id BIGINT, party_type_id BIGINT, preferred_language_id BIGINT, gender_id BIGINT, department_id BIGINT, qr_code_id BIGINT, require_ojt BOOLEAN
JOINS:
  department_id -> masters.product_store.id
  gender_id -> public.gender [unverified].id
  party_type_id -> masters.party_type.id
  preferred_language_id -> public.language [unverified].id
  qr_code_id -> public.qr_code [unverified].id
  status_id -> masters.status/lms.status.id

TABLE masters.status (bridge)
PURPOSE: A table that defines the status values used across the system to represent the lifecycle or condition of entities.
COLUMNS: id BIGINT, name VARCHAR(60), sequence_no INTEGER, description VARCHAR(100), type VARCHAR(60), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, category_id BIGINT
JOINS:
  category_id -> masters.status_category/lms.status_category.id

TABLE lms.status (lookup)
PURPOSE: A table that defines the status values used across the learning management system (LMS) to represent the current state of entities such as courses, enrollments, or tasks.
COLUMNS: id BIGINT, name VARCHAR(60), sequence_no INTEGER, description VARCHAR(100), type VARCHAR(60), category_id BIGINT
JOINS:
  category_id -> masters.status_category/lms.status_category.id

TABLE masters.party_type (lookup)
PURPOSE: A classification system for categorizing different types of parties in the system.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(255)

TABLE masters.product_store_type (lookup)
PURPOSE: This table defines the types of store structures or organizational units that can be associated with products in the system. It provides a classification system for how products are organized or sold within the store.
COLUMNS: id BIGINT, name VARCHAR(25), description VARCHAR(60), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE

TABLE masters.status_category (lookup)
PURPOSE: A classification system used to categorize the status of entities within an enterprise system.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(100), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE

====================================================================================================
Q: which security group does a user belong to
-> 12 tables total (6 anchor, 2 bridge, 4 lookup)

Anchor scores (table | final | semantic | lexical):
  masters.security_group         1.169   0.794   0.750
  masters.product_store_user_group 0.889   0.639   0.500
  masters.party                  0.857   0.607   0.500
  pc.sys_authority               0.785   0.535   0.500
  lms.status_category            0.749   0.499   0.500
  pc.sys_user                    0.739   0.614   0.250

Bridges: ['masters.status', 'pc.sys_user_authority']
Lookups: ['lms.status', 'masters.mod', 'masters.party_type', 'masters.status_category']

TABLE masters.security_group (anchor)
PURPOSE: A collection of users or systems that are granted specific access rights or permissions to resources within an enterprise system.
COLUMNS: id BIGINT, name VARCHAR(255), code VARCHAR(255), from_date TIMESTAMP WITHOUT TIME ZONE, thru_date TIMESTAMP WITHOUT TIME ZONE, description VARCHAR(255), status_id BIGINT, mod_id BIGINT
JOINS:
  mod_id -> masters.mod.id
  status_id -> masters.status/lms.status.id

TABLE masters.product_store_user_group (anchor)
PURPOSE: This table represents the association between user groups, product stores, and parties (such as customers or organizations) in the context of access control or role-based permissions.
COLUMNS: id BIGINT, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, user_group_id BIGINT, product_store_id BIGINT, party_id BIGINT, from_date DATE, thru_date DATE, remarks VARCHAR(255)
JOINS:
  party_id -> masters.party.id
  product_store_id -> masters.product_store.id
  user_group_id -> public.user_group [unverified].id

TABLE masters.party (anchor)
PURPOSE: A central entity representing individuals or entities (such as users, employees, or customers) within the system.
COLUMNS: id BIGINT, first_name VARCHAR(100), last_name VARCHAR(100), display_name VARCHAR(100), profile_picture OID, profile_picture_content_type VARCHAR(255), email VARCHAR(75), birthdate TIMESTAMP WITHOUT TIME ZONE, notes VARCHAR(255), mobile_number VARCHAR(14), date_of_joining TIMESTAMP WITHOUT TIME ZONE, training_completed_date TIMESTAMP WITHOUT TIME ZONE, jd_approved_on TIMESTAMP WITHOUT TIME ZONE, is_temporary_password BOOLEAN, employee_id VARCHAR(255), auth_string TEXT, user_group_string TEXT, require_induction BOOLEAN, nature_of_intro VARCHAR(25), exp VARCHAR(2), total_exp VARCHAR(2), on_long_leave BOOLEAN, leave_date DATE, rejoin_date DATE, login_attempts INTEGER, reset_remarks VARCHAR(60), reactivate_time TIMESTAMP WITHOUT TIME ZONE, force_password_change TIMESTAMP WITHOUT TIME ZONE, prev_emp TEXT, education TEXT, token VARCHAR(255), ip VARCHAR(255), session_id VARCHAR(255), exit_date DATE, reset_by_user_id BIGINT, user_id BIGINT, created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, status_id BIGINT, party_type_id BIGINT, preferred_language_id BIGINT, gender_id BIGINT, department_id BIGINT, qr_code_id BIGINT, require_ojt BOOLEAN
JOINS:
  department_id -> masters.product_store.id
  gender_id -> public.gender [unverified].id
  party_type_id -> masters.party_type.id
  preferred_language_id -> public.language [unverified].id
  qr_code_id -> public.qr_code [unverified].id
  status_id -> masters.status/lms.status.id

TABLE pc.sys_authority (anchor)
PURPOSE: A list of predefined roles or permissions that define what actions users can perform within the system.
COLUMNS: name VARCHAR(50)

TABLE lms.status_category (anchor)
PURPOSE: A classification system that categorizes different types of status entries within a learning management system.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(100)

TABLE pc.sys_user (anchor)
PURPOSE: A record representing a user within the system, including authentication, personal details, and activity tracking.
COLUMNS: id BIGINT, login VARCHAR(50), password_hash VARCHAR(60), first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(191), image_url VARCHAR(256), activated BOOLEAN, lang_key VARCHAR(10), activation_key VARCHAR(20), reset_key VARCHAR(20), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, reset_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, login_attempts INTEGER, emp_id VARCHAR(255), is_temp_password BOOLEAN, force_change_pwd TIMESTAMP WITHOUT TIME ZONE

TABLE masters.status (bridge)
PURPOSE: A table that defines the status values used across the system to represent the lifecycle or condition of entities.
COLUMNS: id BIGINT, name VARCHAR(60), sequence_no INTEGER, description VARCHAR(100), type VARCHAR(60), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE, category_id BIGINT
JOINS:
  category_id -> masters.status_category/lms.status_category.id

TABLE pc.sys_user_authority (bridge)
PURPOSE: This table maps users to their assigned authorities or roles within the system.
COLUMNS: user_id BIGINT, authority_name VARCHAR(50)
JOINS:
  authority_name -> pc.sys_authority.name
  user_id -> pc.sys_user.id

TABLE lms.status (lookup)
PURPOSE: A table that defines the status values used across the learning management system (LMS) to represent the current state of entities such as courses, enrollments, or tasks.
COLUMNS: id BIGINT, name VARCHAR(60), sequence_no INTEGER, description VARCHAR(100), type VARCHAR(60), category_id BIGINT
JOINS:
  category_id -> masters.status_category/lms.status_category.id

TABLE masters.mod (lookup)
PURPOSE: A module represents a distinct functional or logical unit within a system, often used to categorize or organize components, features, or systems.
COLUMNS: id BIGINT, name VARCHAR(255), description VARCHAR(255)

TABLE masters.party_type (lookup)
PURPOSE: A classification system for categorizing different types of parties in the system.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(255)

TABLE masters.status_category (lookup)
PURPOSE: A classification system used to categorize the status of entities within an enterprise system.
COLUMNS: id BIGINT, name VARCHAR(60), description VARCHAR(100), created_by VARCHAR(50), created_date TIMESTAMP WITHOUT TIME ZONE, last_modified_by VARCHAR(50), last_modified_date TIMESTAMP WITHOUT TIME ZONE